import 'dart:io';

import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

class FileIconManager {
  final Map<String, Map<String, String>> _pathIcons = {
    "_f_abc": {"iconPath": "assets/ext/abc.svg"},
    "_f_azure-pipelines": {"iconPath": "assets/ext/azure-pipelines.svg"},
    "_f_astro": {"iconPath": "assets/ext/astro.svg"},
    "_f_autohotkey": {"iconPath": "assets/ext/autohotkey.svg"},
    "_f_autoit": {"iconPath": "assets/ext/autoit.svg"},
    "_f_angular": {"iconPath": "assets/ext/angular.svg"},
    "_f_angular-component": {"iconPath": "assets/ext/angular-component.svg"},
    "_f_angular-directive": {"iconPath": "assets/ext/angular-directive.svg"},
    "_f_angular-guard": {"iconPath": "assets/ext/angular-guard.svg"},
    "_f_angular-pipe": {"iconPath": "assets/ext/angular-pipe.svg"},
    "_f_angular-resolver": {"iconPath": "assets/ext/angular-resolver.svg"},
    "_f_angular-service": {"iconPath": "assets/ext/angular-service.svg"},
    "_f_ansible": {"iconPath": "assets/ext/ansible.svg"},
    "_f_actionscript": {"iconPath": "assets/ext/actionscript.svg"},
    "_f_advpl_include": {"iconPath": "assets/ext/advpl_include.svg"},
    "_f_advpl_prw": {"iconPath": "assets/ext/advpl_prw.svg"},
    "_f_advpl_ptm": {"iconPath": "assets/ext/advpl_ptm.svg"},
    "_f_advpl_tlpp": {"iconPath": "assets/ext/advpl_tlpp.svg"},
    "_f_apiblueprint": {"iconPath": "assets/ext/apiblueprint.svg"},
    "_f_apps-script": {"iconPath": "assets/ext/apps-script.svg"},
    "_f_appveyor": {"iconPath": "assets/ext/appveyor.svg"},
    "_f_asciidoc": {"iconPath": "assets/ext/asciidoc.svg"},
    "_f_firebase": {"iconPath": "assets/ext/firebase.svg"},
    "_f_terraform": {"iconPath": "assets/ext/terraform.svg"},
    "_f_test-go": {"iconPath": "assets/ext/test-go.svg"},
    "_f_ember": {"iconPath": "assets/ext/ember.svg"},
    "_f_blink": {"iconPath": "assets/ext/blink.svg"},
    "_f_ballerina": {"iconPath": "assets/ext/ballerina.svg"},
    "_f_bazel": {"iconPath": "assets/ext/bazel.svg"},
    "_f_bithound": {"iconPath": "assets/ext/bithound.svg"},
    "_f_blitz": {"iconPath": "assets/ext/blitz.svg"},
    "_f_bower": {"iconPath": "assets/ext/bower.svg"},
    "_f_brainfuck": {"iconPath": "assets/ext/brainfuck.svg"},
    "_f_buck": {"iconPath": "assets/ext/buck.svg"},
    "_f_bun": {"iconPath": "assets/ext/bun.svg"},
    "_f_bucklescript": {"iconPath": "assets/ext/bucklescript.svg"},
    "_f_buildkite": {"iconPath": "assets/ext/buildkite.svg"},
    "_f_cmake": {"iconPath": "assets/ext/cmake.svg"},
    "_f_adonis": {"iconPath": "assets/ext/adonis.svg"},
    "_f_applescript": {"iconPath": "assets/ext/applescript.svg"},
    "_f_ada": {"iconPath": "assets/ext/ada.svg"},
    "_f_android": {"iconPath": "assets/ext/android.svg"},
    "_f_arduino": {"iconPath": "assets/ext/arduino.svg"},
    "_f_elm": {"iconPath": "assets/ext/elm.svg"},
    "_f_apollo": {"iconPath": "assets/ext/apollo.svg"},
    "_f_astyle": {"iconPath": "assets/ext/astyle.svg"},
    "_f_aurelia": {"iconPath": "assets/ext/aurelia.svg"},
    "_f_azure": {"iconPath": "assets/ext/azure.svg"},
    "_f_bitbucket": {"iconPath": "assets/ext/bitbucket.svg"},
    "_f_changelog": {"iconPath": "assets/ext/changelog.svg"},
    "_f_cabal": {"iconPath": "assets/ext/cabal.svg"},
    "_f_cake": {"iconPath": "assets/ext/cake.svg"},
    "_f_capacitor": {"iconPath": "assets/ext/capacitor.svg"},
    "_f_chess": {"iconPath": "assets/ext/chess.svg"},
    "_f_circleci": {"iconPath": "assets/ext/circleci.svg"},
    "_f_clojure": {"iconPath": "assets/ext/clojure.svg"},
    "_f_cloudfoundry": {"iconPath": "assets/ext/cloudfoundry.svg"},
    "_f_coala": {"iconPath": "assets/ext/coala.svg"},
    "_f_cobol": {"iconPath": "assets/ext/cobol.svg"},
    "_f_coconut": {"iconPath": "assets/ext/coconut.svg"},
    "_f_code-climate": {"iconPath": "assets/ext/code-climate.svg"},
    "_f_codecov": {"iconPath": "assets/ext/codecov.svg"},
    "_f_codeowners": {"iconPath": "assets/ext/codeowners.svg"},
    "_f_coffee": {"iconPath": "assets/ext/coffee.svg"},
    "_f_coldfusion": {"iconPath": "assets/ext/coldfusion.svg"},
    "_f_command": {"iconPath": "assets/ext/command.svg"},
    "_f_commitlint": {"iconPath": "assets/ext/commitlint.svg"},
    "_f_contributing": {"iconPath": "assets/ext/contributing.svg"},
    "_f_credits": {"iconPath": "assets/ext/credits.svg"},
    "_f_crystal": {"iconPath": "assets/ext/crystal.svg"},
    "_f_cucumber": {"iconPath": "assets/ext/cucumber.svg"},
    "_f_cuda": {"iconPath": "assets/ext/cuda.svg"},
    "_f_cypress": {"iconPath": "assets/ext/cypress.svg"},
    "_f_d": {"iconPath": "assets/ext/d.svg"},
    "_f_database": {"iconPath": "assets/ext/database.svg"},
    "_f_deno": {"iconPath": "assets/ext/deno.svg"},
    "_f_denizenscript": {"iconPath": "assets/ext/denizenscript.svg"},
    "_f_dependabot": {"iconPath": "assets/ext/dependabot.svg"},
    "_f_h": {"iconPath": "assets/ext/h.svg"},
    "_f_dhall": {"iconPath": "assets/ext/dhall.svg"},
    "_f_dinophp": {"iconPath": "assets/ext/dinophp.svg"},
    "_f_disc": {"iconPath": "assets/ext/disc.svg"},
    "_f_dotjs": {"iconPath": "assets/ext/dotjs.svg"},
    "_f_drawio": {"iconPath": "assets/ext/drawio.svg"},
    "_f_drone": {"iconPath": "assets/ext/drone.svg"},
    "_f_dune": {"iconPath": "assets/ext/dune.svg"},
    "_f_edge": {"iconPath": "assets/ext/edge.svg"},
    "_f_ejs": {"iconPath": "assets/ext/ejs.svg"},
    "_f_email": {"iconPath": "assets/ext/email.svg"},
    "_f_exe": {"iconPath": "assets/ext/exe.svg"},
    "_f_fastlane": {"iconPath": "assets/ext/fastlane.svg"},
    "_f_figma": {"iconPath": "assets/ext/figma.svg"},
    "_f_flash": {"iconPath": "assets/ext/flash.svg"},
    "_f_flow": {"iconPath": "assets/ext/flow.svg"},
    "_f_forth": {"iconPath": "assets/ext/forth.svg"},
    "_f_fortran": {"iconPath": "assets/ext/fortran.svg"},
    "_f_foxpro": {"iconPath": "assets/ext/foxpro.svg"},
    "_f_fsharp": {"iconPath": "assets/ext/fsharp.svg"},
    "_f_fusebox": {"iconPath": "assets/ext/fusebox.svg"},
    "_f_gatsby": {"iconPath": "assets/ext/gatsby.svg"},
    "_f_gcp": {"iconPath": "assets/ext/gcp.svg"},
    "_f_gemfile": {"iconPath": "assets/ext/gemfile.svg"},
    "_f_gemini": {"iconPath": "assets/ext/gemini.svg"},
    "_f_gitpod": {"iconPath": "assets/ext/gitpod.svg"},
    "_f_godot": {"iconPath": "assets/ext/godot.svg"},
    "_f_godot-assets": {"iconPath": "assets/ext/godot-assets.svg"},
    "_f_grain": {"iconPath": "assets/ext/grain.svg"},
    "_f_graphcool": {"iconPath": "assets/ext/graphcool.svg"},
    "_f_gridsome": {"iconPath": "assets/ext/gridsome.svg"},
    "_f_hack": {"iconPath": "assets/ext/hack.svg"},
    "_f_haxe": {"iconPath": "assets/ext/haxe.svg"},
    "_f_hcl": {"iconPath": "assets/ext/hcl.svg"},
    "_f_helm": {"iconPath": "assets/ext/helm.svg"},
    "_f_heroku": {"iconPath": "assets/ext/heroku.svg"},
    "_f_hex": {"iconPath": "assets/ext/hex.svg"},
    "_f_horusec": {"iconPath": "assets/ext/horusec.svg"},
    "_f_hpp": {"iconPath": "assets/ext/hpp.svg"},
    "_f_http": {"iconPath": "assets/ext/http.svg"},
    "_f_husky": {"iconPath": "assets/ext/husky.svg"},
    "_f_hygen": {"iconPath": "assets/ext/hygen.svg"},
    "_f_i18n": {"iconPath": "assets/ext/i18n.svg"},
    "_f_idris": {"iconPath": "assets/ext/idris.svg"},
    "_f_imba": {"iconPath": "assets/ext/imba.svg"},
    "_f_ionic": {"iconPath": "assets/ext/ionic.svg"},
    "_f_istanbul": {"iconPath": "assets/ext/istanbul.svg"},
    "_f_jar": {"iconPath": "assets/ext/jar.svg"},
    "_f_java": {"iconPath": "assets/ext/java.svg"},
    "_f_javaclass": {"iconPath": "assets/ext/javaclass.svg"},
    "_f_jenkins": {"iconPath": "assets/ext/jenkins.svg"},
    "_f_jupyter": {"iconPath": "assets/ext/jupyter.svg"},
    "_f_key": {"iconPath": "assets/ext/key.svg"},
    "_f_kivy": {"iconPath": "assets/ext/kivy.svg"},
    "_f_kotlin": {"iconPath": "assets/ext/kotlin.svg"},
    "_f_authors": {"iconPath": "assets/ext/authors.svg"},
    "_f_auto": {"iconPath": "assets/ext/auto.svg"},
    "_f_django": {"iconPath": "assets/ext/django.svg"},
    "_f_word": {"iconPath": "assets/ext/word.svg"},
    "_f_windicss": {"iconPath": "assets/ext/windicss.svg"},
    "_f_vim": {"iconPath": "assets/ext/vim.svg"},
    "_f_svelte": {"iconPath": "assets/ext/svelte.svg"},
    "_f_sass": {"iconPath": "assets/ext/sass.svg"},
    "_f_less": {"iconPath": "assets/ext/less.svg"},
    "_f_stylus": {"iconPath": "assets/ext/stylus.svg"},
    "_f_postcssconfig": {"iconPath": "assets/ext/postcssconfig.svg"},
    "_f_docker": {"iconPath": "assets/ext/docker.svg"},
    "_f_git": {"iconPath": "assets/ext/git.svg"},
    "_f_readme": {"iconPath": "assets/ext/readme.svg"},
    "_f_html": {"iconPath": "assets/ext/html.svg"},
    "_f_json": {"iconPath": "assets/ext/json.svg"},
    "_f_markdown": {"iconPath": "assets/ext/markdown.svg"},
    "_f_makefile": {"iconPath": "assets/ext/makefile.svg"},
    "_f_mdx": {"iconPath": "assets/ext/mdx.svg"},
    "_f_mdsvex": {"iconPath": "assets/ext/mdsvex.svg"},
    "_f_merlin": {"iconPath": "assets/ext/merlin.svg"},
    "_f_meson": {"iconPath": "assets/ext/meson.svg"},
    "_f_minecraft": {"iconPath": "assets/ext/minecraft.svg"},
    "_f_mocha": {"iconPath": "assets/ext/mocha.svg"},
    "_f_moonscript": {"iconPath": "assets/ext/moonscript.svg"},
    "_f_moon": {"iconPath": "assets/ext/moon.svg"},
    "_f_mxml": {"iconPath": "assets/ext/mxml.svg"},
    "_f_ndst": {"iconPath": "assets/ext/ndst.svg"},
    "_f_nix": {"iconPath": "assets/ext/nix.svg"},
    "_f_npm": {"iconPath": "assets/ext/npm.svg"},
    "_f_nrwl": {"iconPath": "assets/ext/nrwl.svg"},
    "_f_nuget": {"iconPath": "assets/ext/nuget.svg"},
    "_f_ocaml": {"iconPath": "assets/ext/ocaml.svg"},
    "_f_odin": {"iconPath": "assets/ext/odin.svg"},
    "_f_opa": {"iconPath": "assets/ext/opa.svg"},
    "_f_opam": {"iconPath": "assets/ext/opam.svg"},
    "_f_pawn": {"iconPath": "assets/ext/pawn.svg"},
    "_f_percy": {"iconPath": "assets/ext/percy.svg"},
    "_f_perl": {"iconPath": "assets/ext/perl.svg"},
    "_f_pipeline": {"iconPath": "assets/ext/pipeline.svg"},
    "_f_playwright": {"iconPath": "assets/ext/playwright.svg"},
    "_f_powerpoint": {"iconPath": "assets/ext/powerpoint.svg"},
    "_f_processing": {"iconPath": "assets/ext/processing.svg"},
    "_f_posthtml": {"iconPath": "assets/ext/posthtml.svg"},
    "_f_proto": {"iconPath": "assets/ext/proto.svg"},
    "_f_protractor": {"iconPath": "assets/ext/protractor.svg"},
    "_f_puppet": {"iconPath": "assets/ext/puppet.svg"},
    "_f_purescript": {"iconPath": "assets/ext/purescript.svg"},
    "_f_python-misc": {"iconPath": "assets/ext/python-misc.svg"},
    "_f_qsharp": {"iconPath": "assets/ext/qsharp.svg"},
    "_f_r": {"iconPath": "assets/ext/r.svg"},
    "_f_racket": {"iconPath": "assets/ext/racket.svg"},
    "_f_raml": {"iconPath": "assets/ext/raml.svg"},
    "_f_routing": {"iconPath": "assets/ext/routing.svg"},
    "_f_reason": {"iconPath": "assets/ext/reason.svg"},
    "_f_red": {"iconPath": "assets/ext/red.svg"},
    "_f_redhat": {"iconPath": "assets/ext/redhat.svg"},
    "_f_renovate": {"iconPath": "assets/ext/renovate.svg"},
    "_f_replit": {"iconPath": "assets/ext/replit.svg"},
    "_f_restql": {"iconPath": "assets/ext/restql.svg"},
    "_f_riot": {"iconPath": "assets/ext/riot.svg"},
    "_f_roadmap": {"iconPath": "assets/ext/roadmap.svg"},
    "_f_rome": {"iconPath": "assets/ext/rome.svg"},
    "_f_scala": {"iconPath": "assets/ext/scala.svg"},
    "_f_scheme": {"iconPath": "assets/ext/scheme.svg"},
    "_f_search": {"iconPath": "assets/ext/search.svg"},
    "_f_semantic-release": {"iconPath": "assets/ext/semantic-release.svg"},
    "_f_sentry": {"iconPath": "assets/ext/sentry.svg"},
    "_f_serverless": {"iconPath": "assets/ext/serverless.svg"},
    "_f_sequelize": {"iconPath": "assets/ext/sequelize.svg"},
    "_f_settings": {"iconPath": "assets/ext/settings.svg"},
    "_f_sketch": {"iconPath": "assets/ext/sketch.svg"},
    "_f_snowpack": {"iconPath": "assets/ext/snowpack.svg"},
    "_f_san": {"iconPath": "assets/ext/san.svg"},
    "_f_sas": {"iconPath": "assets/ext/sas.svg"},
    "_f_sbt": {"iconPath": "assets/ext/sbt.svg"},
    "_f_shaderlab": {"iconPath": "assets/ext/shaderlab.svg"},
    "_f_siyuan": {"iconPath": "assets/ext/siyuan.svg"},
    "_f_slim": {"iconPath": "assets/ext/slim.svg"},
    "_f_sublime": {"iconPath": "assets/ext/sublime.svg"},
    "_f_slug": {"iconPath": "assets/ext/slug.svg"},
    "_f_snyk": {"iconPath": "assets/ext/snyk.svg"},
    "_f_solidity": {"iconPath": "assets/ext/solidity.svg"},
    "_f_stencil": {"iconPath": "assets/ext/stencil.svg"},
    "_f_stitches": {"iconPath": "assets/ext/stitches.svg"},
    "_f_svgr": {"iconPath": "assets/ext/svgr.svg"},
    "_f_testjsx": {"iconPath": "assets/ext/testjsx.svg"},
    "_f_stryker": {"iconPath": "assets/ext/stryker.svg"},
    "_f_svgo": {"iconPath": "assets/ext/svgo.svg"},
    "_f_swc": {"iconPath": "assets/ext/swc.svg"},
    "_f_table": {"iconPath": "assets/ext/table.svg"},
    "_f_tauri": {"iconPath": "assets/ext/tauri.svg"},
    "_f_tcl": {"iconPath": "assets/ext/tcl.svg"},
    "_f_teal": {"iconPath": "assets/ext/teal.svg"},
    "_f_tobimake": {"iconPath": "assets/ext/tobimake.svg"},
    "_f_todo": {"iconPath": "assets/ext/todo.svg"},
    "_f_template": {"iconPath": "assets/ext/template.svg"},
    "_f_tex": {"iconPath": "assets/ext/tex.svg"},
    "_f_textlint": {"iconPath": "assets/ext/textlint.svg"},
    "_f_twine": {"iconPath": "assets/ext/twine.svg"},
    "_f_uml": {"iconPath": "assets/ext/uml.svg"},
    "_f_sml": {"iconPath": "assets/ext/sml.svg"},
    "_f_vue-config": {"iconPath": "assets/ext/vue-config.svg"},
    "_f_wallaby": {"iconPath": "assets/ext/wallaby.svg"},
    "_f_watchman": {"iconPath": "assets/ext/watchman.svg"},
    "_f_css": {"iconPath": "assets/ext/css.svg"},
    "_f_go-mod": {"iconPath": "assets/ext/go-mod.svg"},
    "_f_cssmap": {"iconPath": "assets/ext/cssmap.svg"},
    "_f_js": {"iconPath": "assets/ext/js.svg"},
    "_f_jsmap": {"iconPath": "assets/ext/jsmap.svg"},
    "_f_typescript": {"iconPath": "assets/ext/typescript.svg"},
    "_f_typescriptdef": {"iconPath": "assets/ext/typescriptdef.svg"},
    "_f_vue": {"iconPath": "assets/ext/vue.svg"},
    "_f_image": {"iconPath": "assets/ext/image.svg"},
    "_f_favicon": {"iconPath": "assets/ext/favicon.svg"},
    "_f_zip": {"iconPath": "assets/ext/zip.svg"},
    "_f_yarn": {"iconPath": "assets/ext/yarn.svg"},
    "_f_error": {"iconPath": "assets/ext/error.svg"},
    "_f_nodejs": {"iconPath": "assets/ext/nodejs.svg"},
    "_f_svg": {"iconPath": "assets/ext/svg.svg"},
    "_f_yaml": {"iconPath": "assets/ext/yaml.svg"},
    "_f_font": {"iconPath": "assets/ext/font.svg"},
    "_f_php": {"iconPath": "assets/ext/php.svg"},
    "_f_phpunit": {"iconPath": "assets/ext/phpunit.svg"},
    "_f_twig": {"iconPath": "assets/ext/twig.svg"},
    "_f_composer": {"iconPath": "assets/ext/composer.svg"},
    "_f_xml": {"iconPath": "assets/ext/xml.svg"},
    "_f_robots": {"iconPath": "assets/ext/robots.svg"},
    "_f_bundler": {"iconPath": "assets/ext/bundler.svg"},
    "_f_stylelint": {"iconPath": "assets/ext/stylelint.svg"},
    "_f_prettier": {"iconPath": "assets/ext/prettier.svg"},
    "_f_python": {"iconPath": "assets/ext/python.svg"},
    "_f_log": {"iconPath": "assets/ext/log.svg"},
    "_f_audio": {"iconPath": "assets/ext/audio.svg"},
    "_f_lua": {"iconPath": "assets/ext/lua.svg"},
    "_f_csharp": {"iconPath": "assets/ext/csharp.svg"},
    "_f_dart": {"iconPath": "assets/ext/dart.svg"},
    "_f_eslint": {"iconPath": "assets/ext/eslint.svg"},
    "_f_handlebars": {"iconPath": "assets/ext/handlebars.svg"},
    "_f_webpack": {"iconPath": "assets/ext/webpack.svg"},
    "_f_ruby": {"iconPath": "assets/ext/ruby.svg"},
    "_f_jest": {"iconPath": "assets/ext/jest.svg"},
    "_f_babel": {"iconPath": "assets/ext/babel.svg"},
    "_f_elixir": {"iconPath": "assets/ext/elixir.svg"},
    "_f_rust": {"iconPath": "assets/ext/rust.svg"},
    "_f_react": {"iconPath": "assets/ext/react.svg"},
    "_f_reactts": {"iconPath": "assets/ext/reactts.svg"},
    "_f_rollup": {"iconPath": "assets/ext/rollup.svg"},
    "_f_gulp": {"iconPath": "assets/ext/gulp.svg"},
    "_f_grunt": {"iconPath": "assets/ext/grunt.svg"},
    "_f_editorconfig": {"iconPath": "assets/ext/editorconfig.svg"},
    "_f_vscode": {"iconPath": "assets/ext/vscode.svg"},
    "_f_visualstudio": {"iconPath": "assets/ext/visualstudio.svg"},
    "_f_ai": {"iconPath": "assets/ext/ai.svg"},
    "_f_photoshop": {"iconPath": "assets/ext/photoshop.svg"},
    "_f_pdf": {"iconPath": "assets/ext/pdf.svg"},
    "_f_go": {"iconPath": "assets/ext/go.svg"},
    "_f_browserslist": {"iconPath": "assets/ext/browserslist.svg"},
    "_f_erlang": {"iconPath": "assets/ext/erlang.svg"},
    "_f_vite": {"iconPath": "assets/ext/vite.svg"},
    "_f_vitest": {"iconPath": "assets/ext/vitest.svg"},
    "_f_mint": {"iconPath": "assets/ext/mint.svg"},
    "_f_env": {"iconPath": "assets/ext/env.svg"},
    "_f_nginx": {"iconPath": "assets/ext/nginx.svg"},
    "_f_c": {"iconPath": "assets/ext/c.svg"},
    "_f_cpp": {"iconPath": "assets/ext/cpp.svg"},
    "_f_powershell": {"iconPath": "assets/ext/powershell.svg"},
    "_f_blade": {"iconPath": "assets/ext/blade.svg"},
    "_f_liquid": {"iconPath": "assets/ext/liquid.svg"},
    "_f_pug": {"iconPath": "assets/ext/pug.svg"},
    "_f_swift": {"iconPath": "assets/ext/swift.svg"},
    "_f_graphql": {"iconPath": "assets/ext/graphql.svg"},
    "_f_groovy": {"iconPath": "assets/ext/groovy.svg"},
    "_f_testjs": {"iconPath": "assets/ext/testjs.svg"},
    "_f_testts": {"iconPath": "assets/ext/testts.svg"},
    "_f_storybook": {"iconPath": "assets/ext/storybook.svg"},
    "_f_webassembly": {"iconPath": "assets/ext/webassembly.svg"},
    "_f_console": {"iconPath": "assets/ext/console.svg"},
    "_f_bat": {"iconPath": "assets/ext/bat.svg"},
    "_f_nuxt": {"iconPath": "assets/ext/nuxt.svg"},
    "_f_next": {"iconPath": "assets/ext/next.svg"},
    "_f_netlify": {"iconPath": "assets/ext/netlify.svg"},
    "_f_vercel": {"iconPath": "assets/ext/vercel.svg"},
    "_f_tailwind": {"iconPath": "assets/ext/tailwind.svg"},
    "_f_windi": {"iconPath": "assets/ext/windi.svg"},
    "_f_nodemon": {"iconPath": "assets/ext/nodemon.svg"},
    "_f_jinja": {"iconPath": "assets/ext/jinja.svg"},
    "_f_haml": {"iconPath": "assets/ext/haml.svg"},
    "_f_smarty": {"iconPath": "assets/ext/smarty.svg"},
    "_f_haskell": {"iconPath": "assets/ext/haskell.svg"},
    "_f_gradle": {"iconPath": "assets/ext/gradle.svg"},
    "_f_nim": {"iconPath": "assets/ext/nim.svg"},
    "_f_nestjs": {"iconPath": "assets/ext/nestjs.svg"},
    "_f_txt": {"iconPath": "assets/ext/txt.svg"},
    "_f_assembly": {"iconPath": "assets/ext/assembly.svg"},
    "_f_certificate": {"iconPath": "assets/ext/certificate.svg"},
    "_f_prisma": {"iconPath": "assets/ext/prisma.svg"},
    "_f_compodoc": {"iconPath": "assets/ext/compodoc.svg"},
    "_f_julia": {"iconPath": "assets/ext/julia.svg"},
    "_f_csv": {"iconPath": "assets/ext/csv.svg"},
    "_f_karma": {"iconPath": "assets/ext/karma.svg"},
    "_f_kl": {"iconPath": "assets/ext/kl.svg"},
    "_f_kusto": {"iconPath": "assets/ext/kusto.svg"},
    "_f_lerna": {"iconPath": "assets/ext/lerna.svg"},
    "_f_lib": {"iconPath": "assets/ext/lib.svg"},
    "_f_lighthouse": {"iconPath": "assets/ext/lighthouse.svg"},
    "_f_lisp": {"iconPath": "assets/ext/lisp.svg"},
    "_f_livescript": {"iconPath": "assets/ext/livescript.svg"},
    "_f_lilypond": {"iconPath": "assets/ext/lilypond.svg"},
    "_f_tsconfig": {"iconPath": "assets/ext/tsconfig.svg"},
    "_f_jsconfig": {"iconPath": "assets/ext/jsconfig.svg"},
    "_f_travis": {"iconPath": "assets/ext/travis.svg"},
    "_f_razor": {"iconPath": "assets/ext/razor.svg"},
    "_f_jsp": {"iconPath": "assets/ext/jsp.svg"},
    "_f_avi": {"iconPath": "assets/ext/avi.svg"},
    "_f_video": {"iconPath": "assets/ext/video.svg"},
    "_f_pnpm": {"iconPath": "assets/ext/pnpm.svg"},
    "_f_remix": {"iconPath": "assets/ext/remix.svg"},
    "_f_mjml": {"iconPath": "assets/ext/mjml.svg"},
    "_f_markojs": {"iconPath": "assets/ext/markojs.svg"},
    "_f_mathematica": {"iconPath": "assets/ext/mathematica.svg"},
    "_f_matlab": {"iconPath": "assets/ext/matlab.svg"},
    "_f_maven": {"iconPath": "assets/ext/maven.svg"},
    "_f_modernizr": {"iconPath": "assets/ext/modernizr.svg"},
    "_f_quasar": {"iconPath": "assets/ext/quasar.svg"},
    "_f_rubocop": {"iconPath": "assets/ext/rubocop.svg"},
    "_f_rescript": {"iconPath": "assets/ext/rescript.svg"},
    "_f_bsconfig": {"iconPath": "assets/ext/bsconfig.svg"},
    "_f_opengl": {"iconPath": "assets/ext/opengl.svg"},
    "_f_llvm": {"iconPath": "assets/ext/llvm.svg"},
    "_f_bicep": {"iconPath": "assets/ext/bicep.svg"},
    "_f_prolog": {"iconPath": "assets/ext/prolog.svg"},
    "_f_lock": {"iconPath": "assets/ext/lock.svg"},
    "_f_lolcode": {"iconPath": "assets/ext/lolcode.svg"},
    "_f_php-cs-fixer": {"iconPath": "assets/ext/php-cs-fixer.svg"},
    "_f_3d": {"iconPath": "assets/ext/3d.svg"},
    "_f_yang": {"iconPath": "assets/ext/yang.svg"},
    "_f_xaml": {"iconPath": "assets/ext/xaml.svg"},
    "_f_wolframlanguage": {"iconPath": "assets/ext/wolframlanguage.svg"},
    "_f_zig": {"iconPath": "assets/ext/zig.svg"},
    "_f_webhint": {"iconPath": "assets/ext/webhint.svg"},
    "_f_wakatime": {"iconPath": "assets/ext/wakatime.svg"},
    "_f_vlang": {"iconPath": "assets/ext/vlang.svg"},
    "_f_virtual": {"iconPath": "assets/ext/virtual.svg"},
    "_f_vfl": {"iconPath": "assets/ext/vfl.svg"},
    "_f_verilog": {"iconPath": "assets/ext/verilog.svg"},
    "_f_velocity": {"iconPath": "assets/ext/velocity.svg"},
    "_f_vala": {"iconPath": "assets/ext/vala.svg"},
    "_f_vagrant": {"iconPath": "assets/ext/vagrant.svg"},
    "_f_url": {"iconPath": "assets/ext/url.svg"},
    "_f_turborepo": {"iconPath": "assets/ext/turborepo.svg"},
    "_f_steadybit": {"iconPath": "assets/ext/steadybit.svg"},
    "_f_tobi": {"iconPath": "assets/ext/tobi.svg"},
    "_f_puppeteer": {"iconPath": "assets/ext/puppeteer.svg"}
  };
  final Map<String, String> _fileExtensions = {
    "wma": "_f_audio",
    "wav": "_f_audio",
    "vox": "_f_3d",
    "tta": "_f_audio",
    "raw": "_f_audio",
    "ra": "_f_audio",
    "opus": "_f_audio",
    "ogg": "_f_audio",
    "oga": "_f_audio",
    "msv": "_f_audio",
    "mpc": "_f_audio",
    "mp3": "_f_audio",
    "mogg": "_f_audio",
    "mmf": "_f_audio",
    "m4p": "_f_audio",
    "m4b": "_f_audio",
    "m4a": "_f_audio",
    "ivs": "_f_audio",
    "iklax": "_f_audio",
    "gsm": "_f_audio",
    "flac": "_f_audio",
    "dvf": "_f_audio",
    "dss": "_f_audio",
    "dct": "_f_audio",
    "au": "_f_audio",
    "ape": "_f_audio",
    "amr": "_f_audio",
    "aiff": "_f_audio",
    "act": "_f_audio",
    "aac": "_f_audio",
    "wmv": "_f_video",
    "webm": "_f_video",
    "vob": "_f_video",
    "svi": "_f_video",
    "rmvb": "_f_video",
    "rm": "_f_video",
    "ogv": "_f_video",
    "nsv": "_f_video",
    "mpv": "_f_video",
    "mpg": "_f_video",
    "mpeg2": "_f_video",
    "mpeg": "_f_video",
    "mpe": "_f_video",
    "mp4": "_f_video",
    "mp2": "_f_video",
    "mov": "_f_video",
    "mk3d": "_f_video",
    "mkv": "_f_video",
    "m4v": "_f_video",
    "m2v": "_f_video",
    "flv": "_f_video",
    "f4v": "_f_video",
    "f4p": "_f_video",
    "f4b": "_f_video",
    "f4a": "_f_video",
    "qt": "_f_video",
    "divx": "_f_video",
    "avi": "_f_video",
    "amv": "_f_video",
    "asf": "_f_video",
    "3gp": "_f_video",
    "3g2": "_f_video",
    "ico": "_f_favicon",
    "tiff": "_f_image",
    "bmp": "_f_image",
    "png": "_f_image",
    "gif": "_f_image",
    "jpg": "_f_image",
    "jpeg": "_f_image",
    "stl": "_f_3d",
    "obj": "_f_3d",
    "ac": "_f_3d",
    "blend": "_f_3d",
    "mesh": "_f_3d",
    "mqo": "_f_3d",
    "pmd": "_f_3d",
    "pmx": "_f_3d",
    "skp": "_f_3d",
    "vac": "_f_3d",
    "vdp": "_f_3d",
    "max": "_f_3d",
    "dwg": "_f_3d",
    "bak": "_f_3d",
    "exr": "_f_3d",
    "abc": "_f_abc",
    "as": "_f_actionscript",
    "ada": "_f_ada",
    "adb": "_f_ada",
    "ads": "_f_ada",
    "ali": "_f_ada",
    "ch": "_f_advpl_include",
    "prx": "_f_advpl_prw",
    "ptm": "_f_advpl_ptm",
    "tlpp": "_f_advpl_tlpp",
    "ai": "_f_ai",
    "apk": "_f_android",
    "smali": "_f_androd",
    "dex": "_f_android",
    "component.ts": "_f_angular-component",
    "component.js": "_f_angular-component",
    "directive.ts": "_f_angular-directive",
    "directive.js": "_f_angular-directive",
    "guard.ts": "_f_angular-guard",
    "guard.js": "_f_angular-guard",
    "pipe.ts": "_f_angular-pipe",
    "pipe.js": "_f_angular-pipe",
    "resolver.ts": "_f_angular-resolver",
    "resolver.js": "_f_angular-resolver",
    "service.ts": "_f_angular-service",
    "service.js": "_f_angular-service",
    "apib": "_f_apiblueprint",
    "apiblueprint": "_f_apiblueprint",
    "applescript": "_f_applescript",
    "ipa": "_f_applescript",
    "gs": "_f_apps-script",
    "ino": "_f_arduino",
    "ad": "_f_asciidoc",
    "adoc": "_f_asciidoc",
    "asciidoc": "_f_asciidoc",
    "asm": "_f_assembly",
    "a51": "_f_assembly",
    "nasm": "_f_assembly",
    "s": "_f_assembly",
    "ms": "_f_assembly",
    "agc": "_f_assembly",
    "ags": "_f_assembly",
    "aea": "_f_assembly",
    "argus": "_f_assembly",
    "miligus": "_f_assembly",
    "binsource": "_f_assembly",
    "astro": "_f_astro",
    "ahk": "_f_autohotkey",
    "au3": "_f_autoit",
    "azcli": "_f_azure",
    "azure-pipelines.yml": "_f_azure-pipelines",
    "azure-pipelines.yaml": "_f_azure-pipelines",
    "bal": "_f_ballerina",
    "balx": "_f_ballerina",
    "bzl": "_f_bazel",
    "bazel": "_f_bazel",
    "bicep": "_f_bicep",
    "blade.php": "_f_blade",
    "inky.php": "_f_blade",
    "blade": "_f_blade",
    "blink": "_f_blink",
    "b": "_f_brainfuck",
    "bf": "_f_brainfuck",
    "cmj": "_f_bucklescript",
    "gemfile": "_f_bundler",
    "gemfile.lock": "_f_bundler",
    "c": "_f_c",
    "i": "_f_c",
    "mi": "_f_c",
    "cabal": "_f_cabal",
    "cake": "_f_cake",
    "crt": "_f_certificate",
    "cer": "_f_certificate",
    "cert": "_f_certificate",
    "pgn": "_f_chess",
    "fen": "_f_chess",
    "clj": "_f_clojure",
    "cljs": "_f_clojure",
    "cljc": "_f_clojure",
    "cmake": "_f_cmake",
    "coarc": "_f_coala",
    "coafile": "_f_coala",
    "cob": "_f_cobol",
    "cbl": "_f_cobol",
    "coco": "_f_coconut",
    ".codeclimate.yml": "_f_code-climate",
    "coffee": "_f_coffee",
    "cson": "_f_coffee",
    "iced": "_f_coffee",
    "cfml": "_f_coldfusion",
    "cfc": "_f_coldfusion",
    "lucee": "_f_coldfusion",
    "cfm": "_f_coldfusion",
    "command": "_f_command",
    "cmd": "_f_console",
    "sh": "_f_console",
    "ksh": "_f_console",
    "csh": "_f_console",
    "tcsh": "_f_console",
    "zsh": "_f_console",
    "bash": "_f_console",
    "bat": "_f_console",
    "awk": "_f_console",
    "fish": "_f_console",
    "exp": "_f_console",
    "cpp": "_f_cpp",
    "cc": "_f_cpp",
    "cxx": "_f_cpp",
    "c++": "_f_cpp",
    "cp": "_f_cpp",
    "mm": "_f_cpp",
    "mii": "_f_cpp",
    "ii": "_f_cpp",
    "cr": "_f_crystal",
    "ecr": "_f_crystal",
    "csx": "_f_csharp",
    "cs": "_f_csharp",
    "css": "_f_css",
    "css.map": "_f_cssmap",
    "feature": "_f_cucumber",
    "cu": "_f_cuda",
    "cuh": "_f_cuda",
    "d": "_f_d",
    "dart": "_f_dart",
    "pdb": "_f_database",
    "sql": "_f_database",
    "pks": "_f_database",
    "pkb": "_f_database",
    "accdb": "_f_database",
    "mdb": "_f_database",
    "sqlite": "_f_database",
    "sqlite3": "_f_database",
    "pgsql": "_f_database",
    "postgres": "_f_database",
    "psql": "_f_database",
    "db": "_f_database",
    "db3": "_f_database",
    "dsc": "_f_denizenscript",
    "dhall": "_f_dhall",
    "dhallb": "_f_dhall",
    "bubble": "_f_dinophp",
    "html.bubble": "_f_dinophp",
    "php.bubble": "_f_dinophp",
    "iso": "_f_disc",
    "djt": "_f_django",
    "dockerignore": "_f_docker",
    "dockerfile": "_f_docker",
    "docker-compose.yml": "_f_docker",
    "docker-compose.yaml": "_f_docker",
    "compose.yaml": "_f_docker",
    "compose.yml": "_f_docker",
    "txt": "_f_document",
    "def": "_f_dotjs",
    "dot": "_f_dotjs",
    "jst": "_f_dotjs",
    "drawio": "_f_drawio",
    "dio": "_f_drawio",
    "drone.yml": "_f_drone",
    "edge": "_f_edge",
    "eex": "_f_elixir",
    "ejs": "_f_ejs",
    "ex": "_f_elixir",
    "exs": "_f_elixir",
    "leex": "_f_elixir",
    "heex": "_f_elixir",
    "elm": "_f_elm",
    "ics": "_f_email",
    "env": "_f_env",
    "erl": "_f_erlang",
    "exe": "_f_exe",
    "msi": "_f_exe",
    "fig": "_f_figma",
    "swf": "_f_flash",
    "woff2": "_f_font",
    "woff": "_f_font",
    "ttf": "_f_font",
    "otf": "_f_font",
    "4th": "_f_forth",
    "fth": "_f_forth",
    "frt": "_f_forth",
    "f": "_f_fortran",
    "f77": "_f_fortran",
    "f90": "_f_fortran",
    "f95": "_f_fortran",
    "f08": "_f_fortran",
    "fxp": "_f_foxpro",
    "prg": "_f_foxpro",
    "fs": "_f_fsharp",
    "fsx": "_f_fsharp",
    "fsi": "_f_fsharp",
    "fsproj": "_f_fsharp",
    "gmi": "_f_gemini",
    "gemini": "_f_gemini",
    "patch": "_f_git",
    "go": "_f_go",
    "gd": "_f_godot",
    "godot": "_f_godot-assets",
    "tres": "_f_godot-assets",
    "tscn": "_f_godot-assets",
    "gradle": "_f_gradle",
    "gr": "_f_grain",
    "graphcool": "_f_graphcool",
    "graphql": "_f_graphql",
    "gql": "_f_graphql",
    "groovy": "_f_groovy",
    "h": "_f_h",
    "haml": "_f_haml",
    "hbs": "_f_handlebars",
    "mustache": "_f_handlebars",
    "hs": "_f_haskell",
    "hx": "_f_haxe",
    "hcl": "_f_hcl",
    "dat": "_f_hex",
    "bin": "_f_hex",
    "hex": "_f_hex",
    "hh": "_f_hpp",
    "hpp": "_f_hpp",
    "hxx": "_f_hpp",
    "h++": "_f_hpp",
    "hp": "_f_hpp",
    "tcc": "_f_hpp",
    "inl": "_f_hpp",
    "html": "_f_html",
    "xhtml": "_f_html",
    "html_vm": "_f_html",
    "asp": "_f_html",
    "http": "_f_http",
    "rest": "_f_http",
    "pot": "_f_i18n",
    "po": "_f_i18n",
    "mo": "_f_i18n",
    "idr": "_f_idris",
    "ibc": "_f_idris",
    "jepg": "_f_image",
    "webp": "_f_image",
    "imba": "_f_imba",
    "jar": "_f_jar",
    "java": "_f_java",
    "jsp": "_f_java",
    "class": "_f_javaclass",
    "jenkins": "_f_jenkins",
    "jinja": "_f_jinja",
    "jinja2": "_f_jinja",
    "j2": "_f_jinja",
    "jinja-html": "_f_jinja",
    "js": "_f_js",
    "cjs": "_f_js",
    "jsconfig": "_f_jsconfig",
    "esx": "_f_js",
    "mjs": "_f_js",
    "js.map": "_f_jsmap",
    "json": "_f_json",
    "tsbuildinfo": "_f_json",
    "json5": "_f_json",
    "jsonl": "_f_json",
    "ndjson": "_f_json",
    "jl": "_f_julia",
    "ipynb": "_f_jupyter",
    "key": "_f_key",
    "pem": "_f_key",
    "pub": "_f_key",
    "asc": "_f_key",
    "gpg": "_f_key",
    "passwd": "_f_key",
    "kv": "_f_kivy",
    "kl": "_f_kl",
    "kt": "_f_kotlin",
    "kts": "_f_kotlin",
    "kql": "_f_kusto",
    "less": "_f_less",
    "lib": "_f_lib",
    "bib": "_f_lib",
    "ly": "_f_lilypond",
    "liquid": "_f_liquid",
    "lisp": "_f_lisp",
    "lsp": "_f_lisp",
    "cl": "_f_lisp",
    "fast": "_f_lisp",
    "ls": "_f_livescript",
    "ll": "_f_llvm",
    "bc": "_f_llvm",
    "log": "_f_log",
    "lock": "_f_lock",
    "lol": "_f_lolcode",
    "makefile": "_f_makefile",
    "md": "_f_markdown",
    "markdown": "_f_markdown",
    "rst": "_f_markdown",
    "marko": "_f_markojs",
    "nb": "_f_mathematica",
    "mex": "_f_matlab",
    "mexn": "_f_matlab",
    "mexrs6": "_f_matlab",
    "mn": "_f_matlab",
    "mum": "_f_matlab",
    "mx": "_f_matlab",
    "mx3": "_f_matlab",
    "rwd": "_f_matlab",
    "slx": "_f_matlab",
    "slddc": "_f_matlab",
    "smv": "_f_matlab",
    "xvc": "_f_matlab",
    "mdx": "_f_mdx",
    "svx": "_f_mdsvex",
    "merlin": "_f_merlin",
    "wrap": "_f_meson",
    "mcfunction": "_f_minecraft",
    "mcmeta": "_f_minecraft",
    "mcr": "_f_minecraft",
    "mca": "_f_minecraft",
    "mcgame": "_f_minecraft",
    "mclevel": "_f_minecraft",
    "mcworld": "_f_minecraft",
    "mine": "_f_minecraft",
    "mus": "_f_minecraft",
    "mint": "_f_mint",
    "mjml": "_f_mjml",
    "moon": "_f_moonscript",
    "mxml": "_f_mxml",
    "ndst.yml": "_f_ndst",
    "ndst.yaml": "_f_ndst",
    "ndst.json": "_f_ndst",
    "nim": "_f_nim",
    "nimble": "_f_nim",
    "nix": "_f_nix",
    "njk": "_f_nunjucks",
    "nunjucks": "_f_nunjucks",
    "ml": "_f_ocaml",
    "mli": "_f_ocaml",
    "cmx": "_f_ocaml",
    "odin": "_f_odin",
    "rego": "_f_opa",
    "opam": "_f_opam",
    "vert": "_f_opengl",
    "frag": "_f_opengl",
    "tesc": "_f_opengl",
    "tese": "_f_opengl",
    "geom": "_f_opengl",
    "comp": "_f_opengl",
    "glsl": "_f_opengl",
    "hlsl": "_f_opengl",
    "pas": "_f_pascal",
    "pwn": "_f_pawn",
    "amx": "_f_pawn",
    "pdf": "_f_pdf",
    "pm": "_f_perl",
    "raku": "_f_perl",
    "psd": "_f_photoshop",
    "php": "_f_php",
    "pipeline": "_f_pipeline",
    "pcss": "_f_postcssconfig",
    "sss": "_f_postcssconfig",
    "pptx": "_f_powerpoint",
    "ppt": "_f_powerpoint",
    "pptm": "_f_powerpoint",
    "potx": "_f_powerpoint",
    "potm": "_f_powerpoint",
    "ppsx": "_f_powerpoint",
    "ppsm": "_f_powerpoint",
    "pps": "_f_powerpoint",
    "ppam": "_f_powerpoint",
    "ppa": "_f_powerpoint",
    "ps1": "_f_powershell",
    "psm1": "_f_powershell",
    "psd1": "_f_powershell",
    "ps1xml": "_f_powershell",
    "psc1": "_f_powershell",
    "pssc": "_f_powershell",
    "prisma": "_f_prisma",
    "pde": "_f_processing",
    "pro": "_f_prolog",
    "p": "_f_prolog",
    "pl": "_f_prolog",
    "proto": "_f_proto",
    "jade": "_f_pug",
    "pug": "_f_pug",
    "pp": "_f_puppet",
    "pure": "_f_purescript",
    "purs": "_f_purescript",
    "py": "_f_python",
    "pyc": "_f_python-misc",
    "whl": "_f_python-misc",
    "qs": "_f_qsharp",
    "r": "_f_r",
    "rmd": "_f_r",
    "rkt": "_f_racket",
    "raml": "_f_raml",
    "cshtml": "_f_razor",
    "vbhtml": "_f_razor",
    "tsx": "_f_reactts",
    "jsx": "_f_react",
    "re": "_f_reason",
    "rei": "_f_reason",
    "red": "_f_red",
    "res": "_f_rescript",
    "resi": "_f_rescript",
    "rql": "_f_restql",
    "restql": "_f_restql",
    "riot": "_f_riot",
    "tag": "_f_riot",
    "routing.ts": "_f_routing",
    "routing.tsx": "_f_routing",
    "routing.js": "_f_routing",
    "routing.jsx": "_f_routing",
    "routes.ts": "_f_routing",
    "routes.tsx": "_f_routing",
    "routes.js": "_f_routing",
    "routes.jsx": "_f_routing",
    "rb": "_f_ruby",
    "erb": "_f_ruby",
    "rake": "_f_ruby",
    "rs": "_f_rust",
    "san": "_f_san",
    "sas": "_f_sas",
    "sas7bdat": "_f_sas",
    "sashdat": "_f_sas",
    "astore": "_f_sas",
    "ast": "_f_sas",
    "sast": "_f_sas",
    "sass": "_f_sass",
    "scss": "_f_sass",
    "sbt": "_f_sbt",
    "scala": "_f_scala",
    "sc": "_f_scala",
    "ss": "_f_scheme",
    "scm": "_f_scheme",
    "code-search": "_f_search",
    "ini": "_f_settings",
    "dlc": "_f_settings",
    "dll": "_f_settings",
    "config": "_f_settings",
    "conf": "_f_settings",
    "properties": "_f_settings",
    "prop": "_f_settings",
    "settings": "_f_settings",
    "option": "_f_settings",
    "props": "_f_settings",
    "toml": "_f_settings",
    "prefs": "_f_settings",
    "sln.dotsettings": "_f_settings",
    "sln.dotsettings.user": "_f_settings",
    "cfg": "_f_settings",
    "unity": "_f_shaderlab",
    "sy": "_f_siyuan",
    "sketch": "_f_sketch",
    "slim": "_f_slim",
    "tpl": "_f_smarty",
    "sml": "_f_sml",
    "mlton": "_f_sml",
    "mlb": "_f_sml",
    "sig": "_f_sml",
    "fun": "_f_sml",
    "cm": "_f_sml",
    "lex": "_f_sml",
    "use": "_f_sml",
    "grm": "_f_sml",
    "sol": "_f_solidity",
    "steadybit.yml": "_f_steadybit",
    "steadybit.yaml": "_f_steadybit",
    "story.js": "_f_storybook",
    "story.jsx": "_f_storybook",
    "story.ts": "_f_storybook",
    "story.tsx": "_f_storybook",
    "story.mdx": "_f_storybook",
    "stories.js": "_f_storybook",
    "stories.jsx": "_f_storybook",
    "stories.ts": "_f_storybook",
    "stories.tsx": "_f_storybook",
    "stories.mdx": "_f_storybook",
    "stories.svelte": "_f_storybook",
    "styl": "_f_stylus",
    "sublime-project": "_f_sublime",
    "sublime-workspace": "_f_sublime",
    "svelte": "_f_svelte",
    "svg": "_f_svg",
    "swc": "_f_swc",
    "swift": "_f_swift",
    "xls": "_f_table",
    "xlsx": "_f_table",
    "csv": "_f_table",
    "tsv": "_f_table",
    "tauri": "_f_tauri",
    "tcl": "_f_tcl",
    "tl": "_f_teal",
    "template": "_f_template",
    "tf": "_f_terraform",
    "tfstate": "_f_terraform",
    "tfvars": "_f_terraform",
    "tf.json": "_f_terraform",
    "test.js": "_f_testjs",
    "test.mjs": "_f_testjs",
    "test.cjs": "_f_testjs",
    "test.snap": "_f_testjs",
    "e2e-spec.js": "_f_testjs",
    "e2e-spec.cjs": "_f_testjs",
    "spec.js": "_f_testjs",
    "spec.mjs": "_f_testjs",
    "spec.cjs": "_f_testjs",
    "spec.tsx": "_f_testjsx",
    "test.tsx": "_f_testjsx",
    "tsx.snap": "_f_testjsx",
    "spec.jsx": "_f_testjsx",
    "test.jsx": "_f_testjsx",
    "jsx.snap": "_f_testjsx",
    "spec.ts": "_f_testts",
    "e2e-spec.ts": "_f_testts",
    "test.ts": "_f_testts",
    "ts.snap": "_f_testts",
    "texi": "_f_tex",
    "sty": "_f_tex",
    "dtx": "_f_tex",
    "ltx": "_f_tex",
    "tobi": "_f_tobi",
    "todo": "_f_todo",
    ".travis.yml": "_f_travis",
    "tsconfig.json": "_f_tsconfig",
    "twig": "_f_twig",
    "tw": "_f_twine",
    "twee": "_f_twine",
    "d.ts": "_f_typescriptdef",
    "ts": "_f_typescript",
    "iuml": "_f_uml",
    "pu": "_f_uml",
    "puml": "_f_uml",
    "plantuml": "_f_uml",
    "wsd": "_f_uml",
    "url": "_f_url",
    "vagrantfile": "_f_vagrant",
    "vala": "_f_vala",
    "vm": "_f_velocity",
    "fhtml": "_f_velocity",
    "vtl": "_f_velocity",
    "vhd": "_f_verilog",
    "sv": "_f_verilog",
    "svh": "_f_verilog",
    "vfl": "_f_vfl",
    "vim": "_f_vim",
    "vimrc": "_f_vim",
    "gvimrc": "_f_vim",
    "exrc": "_f_vim",
    "viminfo": "_f_vim",
    "vdi": "_f_virtual",
    "vbox": "_f_virtual",
    "vbox-prev": "_f_virtual",
    "csproj": "_f_visualstudio",
    "ruleset": "_f_visualstudio",
    "sln": "_f_visualstudio",
    "suo": "_f_visualstudio",
    "vb": "_f_visualstudio",
    "vbs": "_f_visualstudio",
    "vcxitems": "_f_visualstudio",
    "vcxitems.filters": "_f_visualstudio",
    "vcxproj": "_f_visualstudio",
    "vcxproj.filters": "_f_visualstudio",
    "v": "_f_vlang",
    "vsix": "_f_vscode",
    "vsixmanifest": "_f_vscode",
    "vscodeignore": "_f_vscode",
    "code-workplace": "_f_vscode",
    "vue": "_f_vue",
    ".wakatime-project": "_f_wakatime",
    "wasm": "_f_webassembly",
    "wat": "_f_webassembly",
    "wl": "_f_wolframlanguage",
    "wls": "_f_wolframlanguage",
    "doc": "_f_word",
    "docx": "_f_word",
    "rtf": "_f_word",
    "xaml": "_f_xaml",
    "xml": "_f_xml",
    "plist": "_f_xml",
    "xsd": "_f_xml",
    "dtd": "_f_xml",
    "xsl": "_f_xml",
    "xslt": "_f_xml",
    "resx": "_f_xml",
    "iml": "_f_xml",
    "xquery": "_f_xml",
    "tmLanguage": "_f_xml",
    "manifest": "_f_xml",
    "project": "_f_xml",
    "xml.dist": "_f_xml",
    "xml.dist.sample": "_f_xml",
    "dmn": "_f_xml",
    "yaml": "_f_yaml",
    "yml": "_f_yaml",
    "yml.dist": "_f_yaml",
    "yaml.dist": "_f_yaml",
    "YAML-tmLanguage": "_f_yaml",
    "yang": "_f_yang",
    "zig": "_f_zig",
    "zip": "_f_zip",
    "rar": "_f_zip",
    "7z": "_f_zip",
    "tar": "_f_zip",
    "gz": "_f_zip",
    "bzip2": "_f_zip",
    "xz": "_f_zip",
    "bz2": "_f_zip",
    "zipx": "_f_zip",
    "tgz": "_f_zip",
    "lua": "_f_lua"
  };

  Widget getIconPath({required String filePath, double? size}) {
    try {
      final fileName = filePath.split('/').last;
      final extension = _getFileExtension(fileName);

      if (extension != null && _fileExtensions.containsKey(extension)) {
        final iconName = _fileExtensions[extension];
        final String? svgFile = _pathIcons[iconName]?['iconPath'];
        if (svgFile != null) {
          if (iconName == '_f_image') {
            if (iconName == '_f_image') {
              return _imageWidget(filePath, size, svgFile);
            }
          }
          return SvgPicture.asset(
            svgFile,
            width: size ?? 30,
          );
        }
      }

      if (_fileExtensions.containsKey(fileName)) {
        final iconName = _fileExtensions[fileName];
        final String? svgFile = _pathIcons[iconName]?['iconPath'];
        if (svgFile != null) {
          if (iconName == '_f_image') {
            return _imageWidget(filePath, size, svgFile);
          }
          return SvgPicture.asset(
            svgFile,
            width: size ?? 30,
          );
        }
      }

      return Icon(
        Icons.insert_drive_file_sharp,
        size: size ?? 30,
      );
    } catch (e) {
      return Icon(
        Icons.insert_drive_file_sharp,
        size: size ?? 30,
      );
    }
  }

  Widget _imageWidget(String filePath, double? size, String svgFile) {
    final BorderRadius radius = BorderRadius.circular(5);
    if (filePath.startsWith('http')) {
      return Container(
        width: size ?? 30,
        height: size ?? 30,
        decoration: BoxDecoration(
          borderRadius: radius,
          image: DecorationImage(
            image: CachedNetworkImageProvider(
              filePath,
            ),
            fit: BoxFit.cover,
          ),
        ),
      );
    } else {
      final file = File(filePath);
      if (file.existsSync()) {
        return Container(
          width: size ?? 30,
          height: size ?? 30,
          decoration: BoxDecoration(
            borderRadius: radius,
            image: DecorationImage(
              image: Image.file(
                file,
              ).image,
              fit: BoxFit.cover,
            ),
          ),
        );
      } else {
        return SvgPicture.asset(
          svgFile,
          width: size ?? 30,
        );
      }
    }
  }

  String? _getFileExtension(String fileName) {
    final parts = fileName.split('.');
    if (parts.length > 1) {
      return parts.last.toLowerCase();
    }
    return null;
  }
}
